1


In [2]:
import numpy as np

dailywts = 185 - np.arange(5*7)/5

print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [3]:
sats = dailywts[5::7]
suns = dailywts[6::7]

avg = (sats + suns)*0.5
avg

array([183.9, 182.5, 181.1, 179.7, 178.3])

In [44]:
import numpy as np

np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))

locs = np.array([
    [0,4,2],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

x = np.random.randint(1, 9, size=(10,11))
x

array([[3, 1, 8, 1, 2, 1, 6, 8, 6, 5, 6],
       [2, 6, 5, 4, 6, 5, 5, 3, 4, 6, 7],
       [2, 8, 2, 1, 5, 2, 7, 2, 6, 8, 7],
       [1, 3, 3, 7, 8, 5, 8, 3, 1, 1, 3],
       [8, 6, 4, 6, 8, 3, 2, 5, 6, 7, 7],
       [5, 5, 8, 7, 4, 2, 4, 4, 5, 5, 6],
       [8, 1, 6, 2, 8, 1, 6, 8, 5, 8, 5],
       [6, 4, 8, 2, 8, 8, 5, 8, 8, 7, 4],
       [8, 3, 4, 1, 4, 1, 4, 1, 5, 3, 5],
       [6, 8, 5, 8, 7, 4, 2, 4, 4, 7, 6]])

2


In [5]:
gold

array([[2, 3, 0, 5, 2, 0, 3],
       [8, 8, 0, 7, 1, 5, 3],
       [0, 1, 6, 2, 1, 4, 5],
       [4, 0, 8, 9, 9, 8, 7],
       [4, 2, 7, 0, 7, 2, 1],
       [9, 8, 9, 2, 5, 0, 8],
       [1, 9, 8, 2, 6, 4, 3]])

3


In [6]:
OE = np.arange(1, 11)
OE[OE % 2 == 1] = -1
OE[OE % 2 == 0] = (-1) * OE[OE % 2 == 0]
OE

array([ -1,  -2,  -1,  -4,  -1,  -6,  -1,  -8,  -1, -10])

(Այսուհետ պրաքտիս սայտ) 8

In [7]:
Matrix = np.random.randint(10, size = (3,3))
NM = Matrix - Matrix.mean()
NM
Matrix.mean()

4.777777777777778

9

In [8]:
import numpy as np

M = np.random.randint(10, size = (3,3))
np.trace(M)


16

10-11

In [9]:
import numpy as np

arr = np.array([1,2,0,0,5])
Trr = np.nonzero(arr)
Trr


(array([0, 1, 4], dtype=int64),)

12-21


In [10]:
import numpy as np
arr = np.zeros(shape=(9,))
for i in np.arange(0, 3):
    arr[i * 4] = 1
arr

arr2 = np.random.random(size=(9,))


Arr = np.vstack([arr, arr2])
Arr = np.intersect1d(arr, arr2)

Arr = np.random.randint(0,5, size=(5,5))
Arr
np.mean(Arr, axis = 1)



array([3. , 2.8, 1.8, 3. , 1.6])

23

In [11]:
import numpy as np
arr = np.random.randint(1, 9, size = (9,))
arr.max()


8

In [1]:
import numpy as np 

arr = np.random.random((2,2))

arr[arr > 0.5] = 1
arr[arr < 0.5] = 0

1 in arr

True